### ISSUE TITLE
Wrong .NET 4.5.1 dependencies?

### ISSUE THREAD

**Issue by mgnslndh** [spectresystems/commandline#8]
I'm not using .NET Core yet and have no deep knowledge of it but it seems to me that the dependencies for the .NET 4.5.1 nuget package are wrong? Shouldn't it be just `Microsoft.Extensions.CommandLineUtils`?

![image](https://user-images.githubusercontent.com/1139118/28137667-564504d0-674e-11e7-84a6-9d9f4923770a.png)

**Comment by patriksvensson** [comment]
@mgnslndh Thanks for bringing this to my attention. Generated the Nuget packages via Visual Studio since I haven't set up a proper build for this yet. Will fix in next version.

**Comment by patriksvensson** [comment]
@mgnslndh This has been resolved and I will push a new version shortly. I've however removed Microsoft.Extensions.CommandLineUtils since it's not supported, so expected behavior might have changed.
